### ISSUE TITLE
ParameterizedTypeImpl cannot be cast to java.lang.Class

### ISSUE THREAD

**Issue by MadMagezz** [jrcodeza/spring-openapi#21]
If you try to scan controller (to create OpenApi schema), where ReponseEntity has a parameterizedType, then we getting classCast exception. 
**Example of controller method:**

@RequestMapping(value = "/{id}/sequence-flow", method = GET, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<List<FlowElement>> getProcessInstanceSequenceFlows(@PathVariable("id") String id) {
        List<FlowElement> flowElements = processInstanceService.findProcessInstanceFlowElements(id);
        return new ResponseEntity<>(flowElements, HttpStatus.OK);
    }

**Result in terminal:**
[ERROR] Failed to execute goal com.github.jrcodeza:spring-openapi-schema-generator-plugin:1.2.0:generateOpenApi (default) on project open-api-generator: A type incompatibility occurred while executing com.github.jrcodeza:spring-openapi-schema-generator-plugin:1.2.0:generateOpenApi: sun.reflect.generics.reflectiveObjects.ParameterizedTypeImpl cannot be cast to java.lang.Class

**Comment by jrcodeza** [comment]
Hi @MadMagezz 
thanks for bug report. I fixed it, it will be included in 1.2.1 release (expected to be done this weekend). 
I fixed 2 cases:
#1 ResponseEntity<List>
#2 ResponseEntity<List<SomeType>>

However, I think it is better to model REST operation with ResponseEntity<List<SomeType>> approach, because with List only client won't know which types you are returning from operation. In openapi spec this scenario will be generated as follows:

https://gist.github.com/jrcodeza/05b00af30902c4088c7699e22ccdafbc

On the other hand when you also specify List generic type like ResponseEntity<List<SomeType>> it will be generated as:
https://gist.github.com/jrcodeza/0ce6d4bce4bd6fc12fe4621c362b8797

**Comment by jrcodeza** [comment]
Fix for this problem is available in 1.2.1 version or 1.3.0. The 1.3.0 has improved inheritance generation - it uses all of through whole inheritance hierarchy from java class. However, if you want to display spec in swagger-ui you can have problems if you hierarchy is too big (I've got stack overflow in swagger-ui etc.). So if you are using swagger ui I would recommend 1.2.1, if not then 1.3.0. Swagger codegen should work fine with both.

**Comment by MadMagezz** [comment]
Thanks for your reply. Maybe I'm wrong. I'm not the ninja in Java. So I will recheck  for the version (I thought, that I got the latest). I will recheck for controllers (most of them, are not mine and I can't fix them, I can just show the path to the package).

**Comment by jrcodeza** [comment]
Hi @MadMagezz ,
I understand. No problem, with new version that I released it should work in your scenario too. Let me know if some other problems happen I can help ;)
